version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: dpg-ct04giogph6c738gqcj0-a
      DB_PORT: 5432
      DB_NAME: online_voting_system_n0eh
      DB_USERNAME: online_voting_system_n0eh_user
      DB_PASSWORD: Fx5a3YZAdfd4tyO2BA9QPixwcnORi5OT
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: online_voting_system_n0eh
      POSTGRES_USER: online_voting_system_n0eh_user
      POSTGRES_PASSWORD: Fx5a3YZAdfd4tyO2BA9QPixwcnORi5OT
    ports:
      - "5432:5432"
