version: '3.8'

services:
  # Online Voting System Service
  online-voting-system:
    build: .  # Build the Docker image from the Dockerfile in the current directory
    image: votingapp:latest  # Name the built image
    container_name: online-voting-container  # Container name for this service
    ports:
      - "8181:8181"  # Map container's port 8181 to host's port 8181
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/online_voting_system  # Local DB URL
      SPRING_DATASOURCE_USERNAME: sumitpg  # Database username
      SPRING_DATASOURCE_PASSWORD: mailpass  # Database password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Automatic schema updates
      SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: "true"  # Allow bean overriding (use string value)
    networks:
      - voting-network  # Attach this service to the voting-network

# Define custom networks for inter-container communication (you can keep this if needed)
networks:
  voting-network:
    driver: bridge  # Use the default bridge network
  